### ISSUE TITLE
grab_image_mat: method not found

### ISSUE THREAD

**Issue by abeckers** [bluskript/raspicam-rs#3]
I added to my toml:
```
raspicam-rs = "0.1.2"
opencv = "0.70.0"
```
what else do I have to do to activate the feature opencv?

**Comment by abeckers** [comment]
Would be nice, if you could document, that you have to add to the toml
```
raspicam-rs = { version = "0.1.2", features = ["opencv"] }
opencv = "0.70.0"
```
And an example, how to save an image without opencv whould be nice too.

**Comment by bluskript** [comment]
I have documented this usage now
